### ISSUE TITLE
not able to find v4.5

### ISSUE THREAD

**Issue by JinoArch** [stCarolas/setup-maven#30]
I am facing the following issue while running GitHub Actions.

```
Prepare all required actions
Getting action download info
Error: Unable to resolve action `stCarolas/setup-maven@v4.5`, unable to find version `v4.5`
```

Looks like release name/code needs update ? https://github.com/stCarolas/setup-maven/releases ?

updated snippet as 
```
- name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
```

as per https://github.com/marketplace/actions/setup-maven?version=v.4.5 
May be I have to try 4.4!
